[project]
# 从 Supabase 控制台获取的项目 ID
id = "xwrgpngwmdjbmsziuodl"

[api]
# 自动生成的 API URL
url = "https://xwrgpngwmdjbmsziuodl.supabase.co"

[auth]
# 重定向 URL（根据你的前端地址配置）
site_url = "https://std91.icu"
additional_redirect_urls = ["http://localhost:3000"]

[functions]
# Edge Functions 配置
uno-play-card = {}
uno-draw-card = {}
uno-call-uno = {}
